module.exports = [
  {
    id: 1,
    mpid: 0,
    bpid: 0,
    icon: 'home',
    name: '系统首页',
    router: '/',
  },
  {
    id: 2,
    mpid: 0,
    bpid: 0,
    name: '用户权限',
    icon: 'user',
    permission: 'RABC:INDEX',
  },
  {
    id: 21,
    mpid: 2,
    bpid: 1,
    name: '用户管理',
    icon: 'team',
    router: '/users',
    permission: 'USERS:VIEW',
  },
  {
    id: 22,
    mpid: 2,
    bpid: 1,
    name: '角色管理',
    icon: 'solution',
    router: '/roles',
    permission: 'ROLES:VIEW',
  },
  {
    id: 23,
    mpid: 2,
    bpid: 1,
    name: '权限管理',
    icon: 'exception',
    router: '/permissions',
    permission: 'PERMISSIONS:VIEW',
  },
  {
    id: 4,
    mpid: 0,
    bpid: 0,
    name: '基础数据',
    icon: 'hdd',
    permission: 'BDT:INDEX',
  },
  {
    id: 41,
    mpid: 4,
    bpid: 1,
    name: '医院管理',
    icon: 'folder',
    router: '/hospitals',
    permission: 'HOSPITALS:VIEW',
  },
  {
    id: 42,
    mpid: 4,
    bpid: 1,
    name: '科室管理',
    icon: 'folder',
    router: '/departments',
    permission: 'DEPARTMENTS:VIEW',
  },
  {
    id: 43,
    mpid: 4,
    bpid: 1,
    name: '疾病管理',
    icon: 'folder',
    router: '/diseases',
    permission: 'DISEASES:VIEW',
  },
  {
    id: 44,
    mpid: 4,
    bpid: 1,
    name: '医院分类管理',
    icon: 'folder',
    router: '/hospital-cates',
    permission: 'HOS-CATES:VIEW', //
  },
  {
    id: 45,
    mpid: 4,
    bpid: 1,
    name: '标签模板管理',
    icon: 'folder',
    router: '/tag-templates',
    permission: 'TAGS:VIEW', //
  },
  {
    id: 46,
    mpid: 4,
    bpid: 1,
    name: '热词管理',
    icon: 'folder',
    router: '/hot-keywords',
    permission: 'HOT-WORDS:VIEW', //
  },
  {
    id: 5,
    mpid: 0,
    bpid: 0,
    name: '会员管理',
    icon: 'team',
    permission: 'MEMBERS:INDEX',
  },
  {
    id: 51,
    mpid: 5,
    bpid: 1,
    name: '医生列表',
    icon: 'api',
    router: '/doctors',
    permission: 'MEMBERS-DOCTORS:VIEW',
  },
  {
    id: 52,
    mpid: 5,
    bpid: 1,
    name: '医师审核',
    icon: 'api',
    router: '/physician-auths',
    permission: 'PHYSICIAN-AUTHS:VERIFY',
  },
  {
    id: 53,
    mpid: 5,
    bpid: 1,
    name: '资料审核',
    icon: 'api',
    router: '/doctor-profiles',
    permission: 'DOC-PROFILES:VERIFY',

  },
  {
    id: 54,
    mpid: 5,
    bpid: 1,
    name: '职称审核',
    icon: 'api',
    router: '/title-auths',
    permission: 'TITLE-AUTHS:VERIFY',
  },
  {
    id: 55,
    mpid: 5,
    bpid: 1,
    name: '身份证照认证',
    icon: 'api',
    router: '/idcard-pic-auths',
    permission: 'IDPIC-AUTHS:VERIFY',
  },
  {
    id: 6,
    mpid: 0,
    bpid: 0,
    name: '财务管理',
    icon: 'pay-circle-o',
    permission: 'WITHDRAW-BILLS:INDEX',
  },
  {
    id: 61,
    mpid: 6,
    bpid: 1,
    name: '提现管理',
    icon: 'calculator',
    router: '/withdraw-bills',
    permission: 'WITHDRAW-BILLS:VIEW',
  },
  {
    id: 7,
    mpid: 0,
    bpid: 0,
    name: '订单管理',
    icon: 'team',
    permission: 'ORDERS:INDEX', //
  },
  {
    id: 71,
    mpid: 7,
    bpid: 1,
    name: '视频咨询',
    icon: 'api',
    router: '/video-orders',
    permission: 'VIDEO-ORDERS:VIEW', //
  },
  {
    id: 8,
    mpid: 0,
    bpid: 0,
    name: '会诊业务',
    icon: 'solution',
    permission: 'REMOTE-CONSULT:INDEX', //
  },
  {
    id: 81,
    mpid: 8,
    bpid: 1,
    name: '会诊订单管理',
    icon: 'api',
    router: '/remote-consult',
    permission: 'REMOTE-CONSULT:VIEW', //
  },
  {
    id: 82,
    mpid: 8,
    bpid: 1,
    name: '会诊账户管理',
    icon: 'api',
    router: '/rc-hospital',
    permission: 'RC-HOS:VIEW', //
  },
  {
    id: 9,
    mpid: 0,
    bpid: 0,
    name: '客服管理',
    icon: 'customer-service',
    permission: 'CUS-SERVICE:INDEX', //
  },
  {
    id: 91,
    mpid: 9,
    bpid: 1,
    name: '帮助文档',
    icon: 'layout',
    router: '/help',
    permission: 'HELP:VIEW', //
  },
  {
    id: 92,
    mpid: 9,
    bpid: 2,
    name: '提问列表',
    icon: 'layout',
    router: '/questions',
    permission: 'QUESTIONS:VIEW', //
  },
  {
    id: 10,
    mpid: 0,
    bpid: 0,
    name: '开发者工具',
    icon: 'customer-service',
    permission: 'TOOLS:INDEX', //
  },
  {
    id: 101,
    mpid: 10,
    bpid: 1,
    name: '解除订单',
    icon: 'layout',
    router: '/order-cancel',
    permission: 'ORDER-CANCEL:VIEW',
  },
  {
    id: 11,
    mpid: 0,
    bpid: 0,
    name: '代理商管理',
    icon: 'layout',
    permission: 'TOOLS:INDEX',
  },
  {
    id: 111,
    mpid: 11,
    bpid: 1,
    name: '代理商列表',
    icon: 'layout',
    router: '/agencies',
  },
  {
    id: 112,
    mpid: 11,
    bpid: 2,
    name: '代理商提现',
    icon: 'layout',
    router: '/agencies/withdraw-bills',
  },
]
